export { default as Error404Illustration } from './error404.svg?react'
export { default as Error500Illustration } from './error500.svg?react'
export { default as LightBulbIllustration } from './lightbulb.svg?react'
export { default as SchoolBoardIllustration } from './schoolboard.svg?react'
export { default as UserInfoIllustration } from './userinfo.svg?react'
